functionsDirectory = "/Users/annafriesen/RRate/rrate/netlify/functions"
functionsDirectoryOrigin = "config"
redirectsOrigin = "config"
plugins = []
headers = []

[build]
publish = "/Users/annafriesen/RRate/rrate/dist/web"
publishOrigin = "config"
commandOrigin = "config"
command = "expo export"
functions = "/Users/annafriesen/RRate/rrate/netlify/functions"

[build.environment]

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]

[functions]

[[redirects]]
from = "/*"
to = "/index.html"
status = 200.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]